### PR TITLE
Preparation for Google Fonts: Reverted to original vertical metrics

### PR DESCRIPTION
**Pull request by yanone**
Your adjustments to the vertical metrics were invalid. I reverted that, but kept all other changes. Please accept this PR before I can push the update. Thank you.

### CODE REVIEW

**Comment by tallchai** [comment]
@yanone Curious to understand what was invalid about the vertical metrics? I referred to [this guide](https://glyphsapp.com/learn/vertical-metrics) on Vertical Metrics (by GlyphsApp) for their calculations & values.

**Comment by tallchai** [comment]
@yanone Checking for an update on the above comment. To further clarify, the Vertical Metrics values and calculations are based on [this guide](https://glyphsapp.com/learn/vertical-metrics) and the values are higher because we need to accommodate the Devanagari Matras (top and bottom). You can observe similar pattern in Devanagari fonts like Poppins, Mukta and Baloo etc.

**Comment by yanone** [comment]
I haven't forgotten about you. My desk is too full to always reply in a timely manner. My apologies.

So, I'm not going to read through the Glyphs.app tutorial on vertical metrics right now. Google Fonts has their own preferences for vertical metrics, which are [outlined here](https://github.com/googlefonts/gf-docs/tree/main/VerticalMetrics). We’re currently transitioning to a new specification document, but its content won’t change, so this is the relevant documentation for you for the time being.

Our fontbakery tests are supposed to check/enforce these guidelines, so I let Akshar pass initially because no problem was reported. If we indeed have a problem here, this hints at fontbakery checks not functioning satisfactorily for the specific script, which is very possible. I'll look into the details after you helped me understand the issue better.

A few things to note: 
* For updates, line height must match the previous version. This is an update only shortly after the initial release, which means A) you should have properly calculated the metrics from the start since glyphs didn't change since then and B) since the initial release is so young, I may be able to talk our elders into accepting a line height change if it's important, since not very many website will be using Akshar yet. So there *may* be a window of opportunity, but I can't guarantee it.
* If this is about glyphs being cut off top or bottom in certain apps, you may modulate the winAscent/Descent values for that, keeping the line height intact which is expressed through the hhea/typo metrics.
* Vertical metrics must be identical across all masters. This is self-explanatory, but it may not be referenced in the documentation. I'll make sure to add it. The reason is simple: If masters have different vertical metrics, lines set in different weights of a family will show different line height. So you would use the highest/lowest point across all masters as the basis for your calculations, then apply the same numbers to all masters. This was not the case in the recent update.
* For variable fonts, only the vertical metrics of the origin master are used. So your differing metrics across masters actually have no effect on variable fonts. However, Google Fonts also creates static instances from variable fonts and serves those to browser environments that are not capable of displaying variable fonts, and then the vertical metrics of the different masters are interpolated and static instances inherit those interpolated metrics. Also, the fonts that you download on fonts.google.com as zip files are those static instances.

Now, please help me understand the specific issue better. The way I see it, the matras top out at 930 units. The winAscent is set to 990, so way ahead. hhea/typo ascender values are 900, which is lower, but this only affects the line height, not rendering being cut off. You have a 150 units line gap, which looks like ample space to accommodate for ascenders and descenders.

Could you please help me build a case for this? Please demonstrate where lines collide or glyphs are cut off in rendering that mandates a vertical metrics change for an upgrade.
Thank you for your time and effort.

**Comment by tallchai** [comment]
@yanone Thanks for the detailed response. I understand your point.

Reason behind this change:
In additional Devanagari testing, it was found that some of the matras (top and bottom) were getting overlapped. The motivation behind this change was to fix that. Here's a screenshot showing the issue:
Screen Shot 2022-05-04 at 10 50 51 AM

You can also visit [Akshar's Devanagari subset page on Google Fonts](https://fonts.google.com/specimen/Akshar?subset=devanagari) and see the lower matras getting clipped 
Screen Shot 2022-05-04 at 11 07 55 AM

Fontbakery may not have caught Devanagari issues.

1. When setting the vertical metrics, I set them "more" than the lowest & highest glyph values. I can try to bring those numbers down a bit so that the _delta_ between these two releases is minor. I understand that the vertical metrics need to be same across all masters. Should I change all 4 masters to be the same values (the largest values out of the 4)?

2. In this new version, I am setting `typoLineGap` and `hheaLineGap` to 0. I see that this is also outlined by the [Google Fonts documentation](https://github.com/googlefonts/gf-docs/tree/main/VerticalMetrics). Is this not the right change?

Thanks again for your time and support. :)

**Comment by yanone** [comment]
The line height is determined by the sum of hhea/typo ascent+abs(descent)+linegap. If you return linegap to 0, which is indeed in the specs, then you must add the 150 to either ascent or descent or probably a combination of both, which is permitted in the specs for fonts that are not Latin/Cyrillic/Greek.

In other words, in the sum, please return to your previous 1250 units (900+abs(-200)+150). I didn't mention the linegap not being 0 because fontbakery didn't catch this. This is our fault. I'm currently working on a new fontbakery check that enforces this.

Please see how your lines perform at 1250 units line height (125% of upm). If you still need to adjust the line height beyond 1250, I first need to raise this issue to our team. This should have been done before the initial publication.

Yes, all masters need to have the same values.

The issue with lines being cut off on fonts.google.com is really really stupid: It's a CSS issue that should have been resolved ages ago but everything is too slow. If you increase thatt HTML element's padding, you'll see that the glyphs are completely there. We're aware of this issue.

**Comment by tallchai** [comment]
1. I will try to set the linegap to 0 (the recommended approach) and add the difference as a combination to ascent and descent. But, to fix the issue mentioned above (matras overlapping), it will have to be more than 150. :/
As it's just been days since the font is released, I believe it's ideal to get these changes done now (especially for Devanagari). If you look at other Devanagari fonts in comparison [here](https://fonts.google.com/?subset=devanagari), you can see how almost all of them have a taller line height.
2. Initially, I also thought that the Google Fonts clipping is merely a CSS padding issue. But, I don't think that is correct. The "gf-content-editable" element has a `line-height: initial;` property set on it. This CSS property takes into account the line height that comes with the font. If you increase the line-height to say `120px`, you can see that the font is not clipped anymore. There are other "tall" Devanagari fonts which do **not** have this issue. Examples:
- https://fonts.google.com/specimen/Kalam?subset=devanagari
- https://fonts.google.com/specimen/Amita?subset=devanagari

**Comment by tallchai** [comment]
@yanone 

I have checked and tested these new values that work to **fix the main issue: overlapping of matras** while being less than the values increased last week. Here is what works:
typoAscender = hheaAscender = winAscent = **990**
typoDescender = hheaDescender = -(winDescent) = **-390**
typoLineGap = hheaLineGap = 0 (ensuring the recommended approach).

These values are the lowest change needed for the bug to be fixed. 
This is also in line with required "higher" line heights for other Devanagari fonts.
Can you plz discuss with the "elders" and check if this works? It is important to fix the Devanagari overlap bug. Thanks. :)

Here are the Before+After screenshots highlighting the fix:
BEFORE:
Screen Shot 2022-05-04 at 10 50 51 AM

AFTER:
Screen Shot 2022-05-08 at 1 53 40 PM

**Comment by yanone** [comment]
The line height change is accepted. Please finish up any other changes to the fonts in your repo and I'll take a look next week.

**Comment by yanone** [comment]
I'm gonna delete my PR

**Comment by yanone** [comment]
Actually I'm not sure about deleting it. If you're not using it, please delete it yourself. Thanks

**Comment by tallchai** [comment]
@yanone I have completed the changes as discussed in this PR and pushed the updated glyphs file to my repo (`main`).
Closing this PR. Thanks!

**Pull request closed without merging**
